steps:
- name: node:16
  entrypoint: npm
  args: ['install']
- name: node:16
  entrypoint: npm
  args: ['run', 'create-env']
  env:
    - 'PROD_ACCESS_TOKEN_SECRET=${_ACCESS_TOKEN_SECRET_}'
    - 'PROD_REFRESH_TOKEN_SECRET=${_REFRESH_TOKEN_SECRET_}' 
    - 'PROD_SEEDER_EMAIL_PREFIX=${_SEEDER_EMAIL_PREFIX_}' 
    - 'PROD_SEEDER_EMAIL_SUFFIX=${_SEEDER_EMAIL_SUFFIX_}' 
    - 'PROD_IMGUR_CLIENT_ID=${_IMGUR_CLIENT_ID_}'
    - 'PROD_DB_HOSTNAME=${_DB_HOSTNAME_}'
    - 'PROD_DB_PORT=${_DB_PORT_}'
    - 'PROD_DB_NAME=${_DB_NAME_}'
    - 'PROD_DB_USERNAME=${_DB_USERNAME_}'
    - 'PROD_DB_PASSWORD=${_DB_PASSWORD_}'
    - 'PROD_GCLOUD_STORAGE_BUCKET=${_GCLOUD_STORAGE_BUCKET_}'
    - 'PROD_STORAGE_CONFIG_BUCKET=${_STORAGE_CONFIG_BUCKET_}'
    - 'PROD_SSL_DBKEY_PATH=${_SSL_DBKEY_PATH_}'
    - 'PROD_SSL_DBCERT_PATH=${_SSL_DBCERT_PATH_}'
    - 'PROD_SSL_DBCA_PATH=${_SSL_DBCA_PATH_}'
    - 'PROD_REDIS_USERNAME=${_REDIS_USERNAME_}'
    - 'PROD_REDIS_PASSWORD=${_REDIS_PASSWORD_}'
    - 'PROD_REDIS_HOSTNAME=${_REDIS_HOSTNAME_}'
    - 'PROD_REDIS_PORT=${_REDIS_PORT_}'
- name: node:16
  entrypoint: npm
  args: ['run', 'deploy-config']  
- name: node:16
  entrypoint: npm
  args: ['run', 'deploy-db']
- name: node:16
  entrypoint: npm
  args: ['run', 'undo-deploy-redis']
- name: node:16
  entrypoint: npm
  args: ['run', 'deploy-redis']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'app', 'deploy' ]
