steps:
- name: node:16
  entrypoint: npm
  args: ['install']
- name: node:16
  entrypoint: npm
  args: ['run', 'create-env']
  env:
    - 'PRODUCT_ACCESS_TOKEN_SECRET=${_ACCESS_TOKEN_SECRET_}'
    - 'PRODUCT_REFRESH_TOKEN_SECRET=${_REFRESH_TOKEN_SECRET_}' 
    - 'PRODUCT_SEEDER_EMAIL_PREFIX=${_SEEDER_EMAIL_PREFIX_}' 
    - 'PRODUCT_SEEDER_EMAIL_SUFFIX=${_SEEDER_EMAIL_SUFFIX_}' 
    - 'PRODUCT_IMGUR_CLIENT_ID=${_IMGUR_CLIENT_ID_}'   
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'app', 'deploy' ]